# Generated by Django 5.2 on 2025-09-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('addhar', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('dob', models.DateField()),
                ('mbalance', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
