# Generated by Django 5.2 on 2025-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
