# Generated by Django 5.2 on 2025-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_bank_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='addhar',
            field=models.BigIntegerField(),
        ),
    ]
