# Generated by Django 5.2 on 2025-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_bank_addhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
