# Generated by Django 5.2 on 2025-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_bank_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='pwd',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
